POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLmNlcmFuaWMrMkBnbWFpbC5jb20iLCJleHAiOjE3NDE5NjEwNzAsInVzZXJJZCI6Mn0.li647UlrrVrlONiyAfDRK-N8tlh40os_vMNzM-aZR-o

{
    "name": "Test 3",
    "description": "Description 3",
    "location": "test location 3",
    "dateTime": "2025-01-01T15:30:00.000Z"
}