POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLmNlcmFuaWMrMUBnbWFpbC5jb20iLCJleHAiOjE3NDE5NjUzODMsInVzZXJJZCI6MX0.RWbcM1_HtEoV52AcJ_A_qN16V6SjXIuq1oHaD_dfbaQ

{
    "name": "Test 3",
    "description": "Description 3",
    "location": "test location 3",
    "dateTime": "2025-01-01T15:30:00.000Z"
}