DELETE http://localhost:8080/events/1
content-type: application/json

{
    "name": "Test event new 2",
    "description": "A test event new 2",
    "location": "test location new 2",
    "dateTime": "2025-01-01T15:30:00.000Z"
}