DELETE http://localhost:8080/events/6
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLmNlcmFuaWMrMkBnbWFpbC5jb20iLCJleHAiOjE3NDE5NjEwNzAsInVzZXJJZCI6Mn0.li647UlrrVrlONiyAfDRK-N8tlh40os_vMNzM-aZR-o