GET http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLmNlcmFuaWMrMzNAZ21haWwuY29tIiwiZXhwIjoxNzQxODY4NjIxLCJ1c2VySWQiOjB9.3z0vwVaZjDpQRwh5952L2fuAVrc-_1hmr39u6YTHm80
