POST http://localhost:8080/login
content-type: application/json

{
    "email": "david.ceranic+1@gmail.com",
    "password": "222"
}

# {
#     "email": "david.ceranic+2@gmail.com",
#     "password": "123456sdff2"
# }