PUT http://localhost:8080/events/3
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhdmlkLmNlcmFuaWMrM0BnbWFpbC5jb20iLCJleHAiOjE3NDE5NjIyMTMsInVzZXJJZCI6M30.ITpatBIWSI-V3GdSMZd9ELky8C-ntiby826DMomUlQw 

{
    "name": "Completely new event",
    "description": "Completely new description",
    "location": "test location new 2",
    "dateTime": "2025-01-01T15:30:00.000Z"
}